const OWM_TEAM = 'OWM_TEAM';
const COMMITTEE_CHAIR = 'COMMITTEE_CHAIR';
const COMMITTEE_MEMBER = 'COMMITTEE_MEMBER';
const APPLICANT = 'APPLICANT';

export { OWM_TEAM, COMMITTEE_CHAIR, COMMITTEE_MEMBER, APPLICANT };
