export const mockApplicants = [
	{
		sys_id: '1',
		applicant_name: 'Alice Smith',
		applicant_email: 'alice.smith@email.com',
		state: 'triage',
		primary_focus_area: 'RNA Biology',
		secondary_focus_area: 'Molecular Biology',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '2',
		applicant_name: 'Bob Johnson',
		applicant_email: 'bob.johnson@email.com',
		state: 'scoring',
		primary_focus_area: 'Virology',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '3',
		applicant_name: 'Carol Lee',
		applicant_email: 'carol.lee@email.com',
		state: 'in_review',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '3 out of 3',
	},
	{
		sys_id: '4',
		applicant_name: 'Dave Kim',
		applicant_email: 'dave.kim@email.com',
		state: 'review_complete',
		primary_focus_area: 'Bioinformatics',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '0 out of 3',
	},
	{
		sys_id: '5',
		applicant_name: 'Eve Miller',
		applicant_email: 'eve.miller@email.com',
		state: 'completed',
		primary_focus_area: 'Cancer Biology',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '6',
		applicant_name: 'Frank Moore',
		applicant_email: 'frank.moore@email.com',
		state: 'triage',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '7',
		applicant_name: 'Grace Park',
		applicant_email: 'grace.park@email.com',
		state: 'scoring',
		primary_focus_area: 'Immunology',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '3 out of 3',
	},
	{
		sys_id: '8',
		applicant_name: 'Henry Young',
		applicant_email: 'henry.young@email.com',
		state: 'in_review',
		primary_focus_area: 'Cancer Biology',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '9',
		applicant_name: 'Ivy Chen',
		applicant_email: 'ivy.chen@email.com',
		state: 'review_complete',
		primary_focus_area: 'Bioinformatics',
		secondary_focus_area: 'Genomics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '0 out of 3',
	},
	{
		sys_id: '10',
		applicant_name: 'Jack Lee',
		applicant_email: 'jack.lee@email.com',
		state: 'completed',
		primary_focus_area: 'Immunology',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '11',
		applicant_name: 'Kathy Wu',
		applicant_email: 'kathy.wu@email.com',
		state: 'triage',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '12',
		applicant_name: 'Leo Patel',
		applicant_email: 'leo.patel@email.com',
		state: 'scoring',
		primary_focus_area: 'Cancer Biology',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '3 out of 3',
	},
	{
		sys_id: '13',
		applicant_name: 'Mona Singh',
		applicant_email: 'mona.singh@email.com',
		state: 'in_review',
		primary_focus_area: 'Bioinformatics',
		secondary_focus_area: 'Genomics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '0 out of 3',
	},
	{
		sys_id: '14',
		applicant_name: 'Nina Brown',
		applicant_email: 'nina.brown@email.com',
		state: 'review_complete',
		primary_focus_area: 'Immunology',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '15',
		applicant_name: 'Oscar Diaz',
		applicant_email: 'oscar.diaz@email.com',
		state: 'completed',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '2 out of 3',
	},
];

export const mockTablePagination = {
	hideOnSinglePage: true,
	pageSize: 10,
	pageSizeOptions: [10, 25],
	total: 1,
};

export const mockFocusArea = [
    'Genomics',
    'Cancer Biology',
    'Immunology',
    'Bioinformatics',
    'Molecular Biology',
    'Virology',
    'RNA Biology'
]