export const mockRecommendedApplicants = [
	{
		actual_member_score: 0,
		applicant_email: 'user@mail.com',
		applicant_first_name: 'John',
		applicant_last_name: 'Doe',
		applicant_name: 'Doe, John',
		chair_triage_comment: '',
		chair_triage_status: 'yes',
		committee_comments: '',
		committee_decision: '--',
		interview_recommendation: {
			Maybe: 0,
			No: 0,
			Yes: 0,
		},
		is_app_complete: '',
		maybe: 0,
		no: 0,
		references_sent: '0',
		refferred_to_interview: null,
		referred_to_selecting_official: null,
		scores: [],
		scoring_status: 'Scoring in Progress',
		selected: null,
		state: 'scoring',
		sys_id: '12345',
		total: 0,
		total_received_references: '2 out of 5',
		triage_comments: '',
		triage_status: 'yes',
		yes: 0,
	},
];

export const mockRecommendedApplicantsTablePagination = {
	hideOnSinglePage: true,
	pageSize: 10,
	pagesizeOptions: [10, 25],
	total: 1,
};

export const mockUserRoles = [
	'x_g_nci_app_tracke.vacancy_manager',
	'x_g_nci_app_tracke.committee_member',
	'x_g_nci_app_tracke.user',
	'snc_internal',
];

export const mockApplicantsWithFocusAreas = [
	{
		sys_id: '1',
		applicant_name: 'Alice',
		applicant_email: 'alice@example.com',
		primary_focus_area: 'Biology',
		secondary_focus_area: 'Genetics',
		focus_area: 'Biology, Genetics',
		average_member_score: 90,
		scoring_status: 'Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
	},
	{
		sys_id: '2',
		applicant_name: 'Bob',
		applicant_email: 'bob@example.com',
		primary_focus_area: 'Chemistry',
		secondary_focus_area: 'Physics',
		focus_area: 'Chemistry, Physics',
		average_member_score: 85,
		scoring_status: 'Complete',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
	},
];

export const mockApplicantsWithFocusAreasWithRepeat = [
	{
		sys_id: '1',
		applicant_name: 'Bob',
		applicant_email: 'bob@example.com',
		primary_focus_area: 'Chemistry',
		secondary_focus_area: 'Biology',
		focus_area: 'Chemistry, Physics',
		average_member_score: 85,
		scoring_status: 'Complete',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
	},
	{
		sys_id: '2',
		applicant_name: 'Alice',
		applicant_email: 'alice@example.com',
		primary_focus_area: 'Biology',
		secondary_focus_area: 'Genetics',
		focus_area: 'Biology, Genetics',
		average_member_score: 90,
		scoring_status: 'Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
	},
];

export const mockApplicants = [
	{
		sys_id: '1',
		applicant_name: 'Alice Smith',
		applicant_email: 'alice.smith@email.com',
		state: 'triage',
		primary_focus_area: 'Cancer Biology',
		secondary_focus_area: 'Genomics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '2',
		applicant_name: 'Bob Johnson',
		applicant_email: 'bob.johnson@email.com',
		state: 'scoring',
		primary_focus_area: 'Immunology',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '3',
		applicant_name: 'Carol Lee',
		applicant_email: 'carol.lee@email.com',
		state: 'in_review',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '3 out of 3',
	},
	{
		sys_id: '4',
		applicant_name: 'Dave Kim',
		applicant_email: 'dave.kim@email.com',
		state: 'review_complete',
		primary_focus_area: 'Bioinformatics',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '0 out of 3',
	},
	{
		sys_id: '5',
		applicant_name: 'Eve Miller',
		applicant_email: 'eve.miller@email.com',
		state: 'completed',
		primary_focus_area: 'Cancer Biology',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '6',
		applicant_name: 'Frank Moore',
		applicant_email: 'frank.moore@email.com',
		state: 'triage',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '7',
		applicant_name: 'Grace Park',
		applicant_email: 'grace.park@email.com',
		state: 'scoring',
		primary_focus_area: 'Immunology',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '3 out of 3',
	},
	{
		sys_id: '8',
		applicant_name: 'Henry Young',
		applicant_email: 'henry.young@email.com',
		state: 'in_review',
		primary_focus_area: 'Cancer Biology',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '9',
		applicant_name: 'Ivy Chen',
		applicant_email: 'ivy.chen@email.com',
		state: 'review_complete',
		primary_focus_area: 'Bioinformatics',
		secondary_focus_area: 'Genomics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '0 out of 3',
	},
	{
		sys_id: '10',
		applicant_name: 'Jack Lee',
		applicant_email: 'jack.lee@email.com',
		state: 'completed',
		primary_focus_area: 'Immunology',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '11',
		applicant_name: 'Kathy Wu',
		applicant_email: 'kathy.wu@email.com',
		state: 'triage',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '2 out of 3',
	},
	{
		sys_id: '12',
		applicant_name: 'Leo Patel',
		applicant_email: 'leo.patel@email.com',
		state: 'scoring',
		primary_focus_area: 'Cancer Biology',
		secondary_focus_area: 'Immunology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '3 out of 3',
	},
	{
		sys_id: '13',
		applicant_name: 'Mona Singh',
		applicant_email: 'mona.singh@email.com',
		state: 'in_review',
		primary_focus_area: 'Bioinformatics',
		secondary_focus_area: 'Genomics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 1, No: 0, Maybe: 0 },
		total_received_references: '0 out of 3',
	},
	{
		sys_id: '14',
		applicant_name: 'Nina Brown',
		applicant_email: 'nina.brown@email.com',
		state: 'review_complete',
		primary_focus_area: 'Immunology',
		secondary_focus_area: 'Cancer Biology',
		scoring_status: 'Pending',
		interview_recommendation: { Yes: 0, No: 1, Maybe: 0 },
		total_received_references: '1 out of 3',
	},
	{
		sys_id: '15',
		applicant_name: 'Oscar Diaz',
		applicant_email: 'oscar.diaz@email.com',
		state: 'completed',
		primary_focus_area: 'Genomics',
		secondary_focus_area: 'Bioinformatics',
		scoring_status: 'Scoring Complete',
		interview_recommendation: { Yes: 0, No: 0, Maybe: 1 },
		total_received_references: '2 out of 3',
	},
];

export const mockApplicantFocusArea = [
	'Cancer Biology',
	'Immunology',
	'Bioinformatics',
	'Genomics',
];
