name: Run Unit Tests

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.4'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test